version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: casino-postgres
    hostname: casino-db
    environment:
      TZ: Europe/Warsaw
      POSTGRES_USER: casino
      POSTGRES_PASSWORD: casino
      POSTGRES_DB: casino
    ports:
      - "5432:5432"
    volumes:
      - casino-db:/var/lib/postgresql/data


volumes:
  casino-db: