services:
  user1:
    image: python:3.10-slim
    container_name: casino-user1
    volumes:
      - ./src:/app
    working_dir: /app
    environment:
      PLAYER_EMAIL: "example@example.com"
      PLAYER_FIRST_NAME: "example"
      PLAYER_LAST_NAME: "example"
      POSTGRES_HOST: "casino-db"
    command: bash -c "pip install sqlalchemy psycopg2-binary && python db/App.py"

networks:
  casino-network:
    external: true